### ISSUE TITLE
Bug: PHP Notice:  Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/KanboardEmailHistory#14]
For Project Name / Project Identifier, getting the following error:

```
PHP Notice:  Trying to access array offset on value of type null in /var/www/mydomain.com/public_html/plugins/KanboardEmailHistory/Action/EmailTaskHistory.php on line 72
```
https://github.com/aljawaid/KanboardEmailHistory/blob/bf399c5d76549c7bcfd0f3fab43fe7f17f09322e/Action/EmailTaskHistory.php#L72

Relates to:  #7 Use Project Name & Identifier in Email Subject

**Comment by aljawaid** [comment]
@creecros I think `$project['name']` is called wrong?

Should it be:
`$project = $this->projectModel->getById($data['task']['project_id']);` (worked for email so I moved it for subject too)
- [ ] `$project_id['name']` (because of line 62)
- [ ] `$data['task']['project_id']['name']`
- [ ] `$data['project']['name'])`

**Comment by aljawaid** [comment]
oh wait... it could be the language strings

**Comment by creecros** [comment]
I am still on my phone, but would say none are correct. 

https://github.com/aljawaid/KanboardEmailHistory/blob/f209e2f56927b18ca6d9197221d4a01fdf0a5656/Action/EmailTaskHistory.php#L48

the only event parameter you have is task.

**Comment by aljawaid** [comment]
Does 8b9b031 fix it?

**Comment by aljawaid** [comment]
@creecros I think 29f15a9 is what you meant?

But now, is `$subject = $this->getParam('subject') . ": " . $project['name'] . " " . $project['identifier'];` called correctly?

**Comment by aljawaid** [comment]
@creecros any advice how to call the project name based on the last comment?

**Comment by creecros** [comment]
`$project = $this->projectModel->getById($data['task']['project_id']);` is correct.

and `$project['name']` should now work.

**Comment by aljawaid** [comment]
It still doesnt work, I think my `elseif` might be wrong.... I will look into them again

**Comment by aljawaid** [comment]
@creecros am I right, the above code should be edited as:
1. Remove `== true`
2. Change `&&` to `||`
3. Move the first `if` to the last one, so the `if` checks all the others before 'task title+id' only

**Comment by creecros** [comment]
I'll have to play with it. too much for me to comprehend on my phone. I just haven't had the motivation as of yet. it's tough to get away from wife and kids on the weekends to sit down on a computer.

**Comment by aljawaid** [comment]
I understand, based on what you previously once told me, the `if` statement will stop when it matches what its looking for, which is why Im thinking it wont show an error becuase it never gets past the 'task title+id' if statement... which makes the subject codeblock wrong...

Currently, I think it stops at the first `if`

**Comment by creecros** [comment]
I would say, you are correct, if it hits the first `if` and is true, then the corresponding `else ifs` are ignored.

**Comment by aljawaid** [comment]
> I would say, you are correct, if it hits the first `if` and is true, then the corresponding `else ifs` are ignored.

great, so I need to code it backwards with the most restrictive (less likely option used) first, and the free option (task title+id) as the last... I will work on this tonight, I think I have a solution in my head

**Comment by creecros** [comment]
well, that could work, but the correct way to fix would be to make it bullet proof.

couple ways to do that, but basically, the easiest would be very specific in the statement. 

example:
3 checkboxes, a, b, c
instead of, `if (a)`
use `if (a && !b && !c)`

see the differnce?

**Comment by aljawaid** [comment]
> well, that could work, but the correct way to fix would be to make it bullet proof.
> 
> couple ways to do that, but basically, the easiest would be very specific in the statement. 
> 
> example:
> 3 checkboxes, a, b, c
> instead of, `if (a)`
> use `if (a && !b && !c)`
> 
> see the difference?
> 
> also, `== true` is redundant. 
> `if (a ==true)` is the same as `if (a)`
> and `if (a ==false)` is the same as `if (!a)`
> 
> another method would be to nest the if statements.
> 
> example:
> 3 checkboxes, a, b, c
> ```
> if (a) {
>    if (b) {
>      if (c) {
>     }
>   }
> }
> ```

example:
3 checkboxes, a, b, c
instead of, if (a)
use if (a && !b && !c)

`if (a && !b && !c)`

To get `a` on its own, it would be the `else` right?

**Comment by creecros** [comment]
no, this is a on its own

`if (a && !b && !c)`

in English, its:
if a and not b and not c
